AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template to create network resources for a 3-tier architecture.'

Parameters:
  VpcCidr:
    Type: String
    Default: "10.0.0.0/16"
    Description: "CIDR block for the VPC"

  PublicSubnet1Cidr:
    Type: String
    Default: "10.0.1.0/24"
  
  PublicSubnet2Cidr:
    Type: String
    Default: "10.0.2.0/24"
  
  PrivateSubnet1Cidr:
    Type: String
    Default: "10.0.3.0/24"
  
  PrivateSubnet2Cidr:
    Type: String
    Default: "10.0.4.0/24"

Resources:
  MaverickTechVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      Tags:
        - Key: Name
          Value: MaverickTechVPC

  MyInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: MaverickTechIGW

  VpcGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref MaverickTechVPC
      InternetGatewayId: !Ref MyInternetGateway

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MaverickTechVPC
      CidrBlock: !Ref PublicSubnet1Cidr
      AvailabilityZone: us-east-1a
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: MaverickTechPublicSubnet1

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MaverickTechVPC
      CidrBlock: !Ref PublicSubnet2Cidr
      AvailabilityZone: us-east-1b
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: MaverickTechPublicSubnet2

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MaverickTechVPC
      CidrBlock: !Ref PrivateSubnet1Cidr
      AvailabilityZone: us-east-1a
      Tags:
        - Key: Name
          Value: MaverickTechPrivateSubnet1

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MaverickTechVPC
      CidrBlock: !Ref PrivateSubnet2Cidr
      AvailabilityZone: us-east-1b
      Tags:
        - Key: Name
          Value: MaverickTechPrivateSubnet2

  NatGatewayEIP:
    Type: AWS::EC2::EIP

  NatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatGatewayEIP.AllocationId
      SubnetId: !Ref PublicSubnet1
      Tags:
        - Key: Name
          Value: MaverickTechNatGateway

Outputs:
  VPCId:
    Description: "VPC ID"
    Value: !Ref MaverickTechVPC
    Export:
      Name: !Sub "${AWS::StackName}-VPCId"

  PublicSubnet1Id:
    Description: "Public Subnet 1 ID"
    Value: !Ref PublicSubnet1
    Export:
      Name: !Sub "${AWS::StackName}-PublicSubnet1Id"

  PublicSubnet2Id:
    Description: "Public Subnet 2 ID"
    Value: !Ref PublicSubnet2
    Export:
      Name: !Sub "${AWS::StackName}-PublicSubnet2Id"

  PrivateSubnet1Id:
    Description: "Private Subnet 1 ID"
    Value: !Ref PrivateSubnet1
    Export:
      Name: !Sub "${AWS::StackName}-PrivateSubnet1Id"

  PrivateSubnet2Id:
    Description: "Private Subnet 2 ID"
    Value: !Ref PrivateSubnet2
    Export:
      Name: !Sub "${AWS::StackName}-PrivateSubnet2Id"
